// Frontend/react/src/pages/Login.tsx
import {
  createTheme ,
  CssBaseline , 
  Grid ,
  ThemeProvider
} from '@mui/material'

import LoginSideLogo from '@components/Login/LoginSideLogo'
import LoginForm from '@components/Login/LoginForm'

const theme = createTheme()

export default function LoginPage() {
  return (
    <ThemeProvider theme={ theme } >
      <Grid container component="main" sx={{ height: '100vh' }}>
        <CssBaseline />
        <LoginSideLogo />
        <LoginForm />
      </Grid>
    </ThemeProvider>
  )
}

// Frontend/vue/src/pages/Login.vue
<template>

<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">

      <LoginForm />
      <LoginSideLogo />

    </div>
  </div>
</div>

</template>

<script setup lang="ts">

import {} from 'vuestic-ui'

import LoginForm from '@components/Login/LoginForm.vue'
import LoginSideLogo from '@components/Login/LoginSideLogo.vue'

</script>

<style lang="css" >

</style>
